const express = require("express");
const cors = require("cors");
const error = require("../middlewares/error");
const athlete = require("../routes/athlete");
const staff = require("../routes/staff");
const coachPlan = require("../routes/coachPlan");
const coach = require("../routes/coach");
const sportHistory = require("../routes/sportHistory");
const sub = require("../routes/sub");
const athleteWeight = require("../routes/athleteWeight");
const payment = require("../routes/payment");
const athleteSubPlan = require("../routes/athleteSubPlan");
const coachSubPlan = require("../routes/coachSubPlan");
const subCloset = require("../routes/subCloset");
const owner = require("../routes/owner");
const entrance = require("../routes/entrance");
const secretary = require("../routes/secretary");
module.exports = function (app) {
  app.use(cors());
  app.use(express.json());
  app.use("/athlete", athlete);
  app.use("/athlete/sport_history", sportHistory);
  app.use("/athlete/athlete_weight", athleteWeight);
  app.use("/athlete/sub_plan", athleteSubPlan);
  app.use("/sub/payment", payment);
  app.use("/sub", sub);
  app.use("/sub/sub_closet", subCloset);
  app.use("/staff", staff);
  app.use("/coach/coach_plan", coachPlan);
  app.use("/coach", coach);
  app.use("/coach/sub_plan", coachSubPlan);
  app.use("/owner", owner);
  app.use("/entrance", entrance);
  app.use("/secretary", secretary);
  app.use(error);
};
